### ISSUE TITLE
Use `jsx-no-literals` to prevent introducing untranslated strings

### ISSUE THREAD

**Issue by paulkaplan** [LLK/eslint-config-scratch#10]
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-literals.md

/cc @rschamp @chrisgarrity

**Comment by rschamp** [comment]
Why?

**Comment by paulkaplan** [comment]
Same issue is filed on scratch-gui https://github.com/LLK/scratch-gui/issues/527
