### ISSUE TITLE
Can we move to no warnings?

### ISSUE THREAD

**Issue by paulkaplan** [LLK/eslint-config-scratch#11]
Warnings are universally ignored. Can we decide whether the warnings are important or not and change them to errors?

**Comment by thisandagain** [comment]
Major +1 on this.

**Comment by rschamp** [comment]
Here are the current warnings. How about people check off the ones they want to be errors, we remove the rest? 

I think there is utility in leaving one as a warning — `no-warning-comments`, as this highlights `TODO`/`FIXME` items — I think that's useful to have in the code, but we should lint and convert them into issues periodically.

### Base
- [X] [array-callback-return](http://eslint.org/docs/rules/array-callback-return) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/index.js#L26
- [ ] [block-scoped-var](http://eslint.org/docs/rules/block-scoped-var) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/index.js#L27
- [X] [no-else-return](http://eslint.org/docs/rules/no-else-return) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/index.js#L34
- [X] [no-extra-bind](http://eslint.org/docs/rules/no-extra-bind) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/index.js#L38
- [X] [no-new](http://eslint.org/docs/rules/no-new) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/index.js#L47
- [X] [no-restricted-properties](http://eslint.org/docs/rules/no-restricted-properties) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/index.js#L49-L53
- [X] [no-sequences](http://eslint.org/docs/rules/no-sequences) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/index.js#L57
- [X] [no-unmodified-loop-condition](http://eslint.org/docs/rules/no-unmodified-loop-condition) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/index.js#L59
- [X] [no-useless-concat](http://eslint.org/docs/rules/no-useless-concat) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/index.js#L62
- [ ] [no-warning-comments](http://eslint.org/docs/rules/no-warning-comments) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/index.js#L64-L66
- [X] [no-lonely-if](http://eslint.org/docs/rules/no-lonely-if) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/index.js#L114
- [X] [no-mixed-operators](http://eslint.org/docs/rules/no-mixed-operators) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/index.js#L115
- [X] [no-negated-condition](http://eslint.org/docs/rules/no-negated-condition) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/index.js#L121
- [ ] [require-jsdoc](http://eslint.org/docs/rules/require-jsdoc) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/index.js#L136

### ES6
- [X] [prefer-const](http://eslint.org/docs/rules/prefer-const) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/es6.js#L14

### Node
- [X] [handle-callback-err](http://eslint.org/docs/rules/handle-callback-err) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/node.js#L5

### React
- [X] [no-string-refs](https://github.com/yannickcr/eslint-plugin-react/blob/dae6574e4d426bacd311b3fe438bcc35e7461530/docs/rules/no-string-refs.md) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/react.js#L19
- [ ] [prefer-stateless-function](https://github.com/yannickcr/eslint-plugin-react/blob/dae6574e4d426bacd311b3fe438bcc35e7461530/docs/rules/prefer-stateless-function.md) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/react.js#L24
- [X] [jsx-no-bind](https://github.com/yannickcr/eslint-plugin-react/blob/dae6574e4d426bacd311b3fe438bcc35e7461530/docs/rules/jsx-no-bind.md) https://github.com/LLK/eslint-config-scratch/blob/4ccd256b9436f5908062b409933d57b516f1334e/react.js#L46-L48

**Comment by cwillisf** [comment]
> I think there is utility in leaving one as a warning — no-warning-comments, as this highlights TODO/FIXME items — I think that's useful to have in the code, but we should lint and convert them into issues periodically.

+1

**Comment by paulkaplan** [comment]
> I think there is utility in leaving one as a warning — no-warning-comments, as this highlights TODO/FIXME items — I think that's useful to have in the code, but we should lint and convert them into issues periodically.

-1 I disagree. I think it is fine to note those things in the code, and it is good to have a format (i.e. `@todo`) but you can always ctrl+F through the code to find that. I don't see why we would rely on linting to find it. If you want to use `@todo` in your development process (like pre-pr) then you can turn it on as an error?

**Comment by cwillisf** [comment]
> you can always ctrl+F through the code to find that. I don't see why we would rely on linting to find it.

In my mind, spitting out lint warnings for `@todo` items is about making sure we're aware of them even when we're not actively looking for them. In the bigger picture, it's about motivating us to fix our `@todo` items.

The most convincing argument I can think of against my current position is to say that these items should either be turned into tracked issues (we really should `@todo` it) or we shouldn't worry about them (if it's not so important / it's a nice-to-have).

> If you want to use `@todo` in your development process (like pre-pr) then you can turn it on as an error?

I think I'd be OK with this, though I would prefer either having it turned on as a warning at all times or officially declaring "issue or it won't happen" and avoiding `@todo`.

**Comment by paulkaplan** [comment]
Δ yeah, i'm softened on this. Particularly because i just encountered several useful todo comments in the code while doing some refactoring :)

**Comment by cwillisf** [comment]
I looked at all the warnings that don't have their boxes checked in [Ray's comment above](https://github.com/LLK/eslint-config-scratch/issues/11#issuecomment-321628091). I think my feeling is that all of those should become errors, except for the `@todo` stuff that @paulkaplan and I have been discussing :)

That means quite a bit of cleanup in `scratch-vm`, though. Maybe the `eslint` auto-fix can handle most of it...

**Comment by rschamp** [comment]
@cwillisf You mean that we should check off `block-scoped-var` and `no-restricted-properties`?

**Comment by cwillisf** [comment]
(hits F5)
...oh. There are more boxes checked now than I thought ;)

`block-scoped-var`: I'm in favor of this being treated as an error, though I'm not sure it'll come up much given that most of our code is using the ES6 ruleset, including `no-var` and `prefer-const`.

`no-restricted-properties`: I actually missed this one when I was looking through the list. Do we use this right now?

**Comment by chrisgarrity** [comment]
If we turn on `require-jsdoc`, what would be the required options? The defaults are: 
```
"require": {
            "FunctionDeclaration": true,
            "MethodDefinition": false,
            "ClassDeclaration": false,
            "ArrowFunctionExpression": false
        }
```
That only requires doc on functions. Seems like we might want more.

**Comment by colbygk** [comment]
I am in favor of having errors only, with the todo items being masked off
via

    // eslint-disable-next-line no-warning-comments

- Colby

**Comment by paulkaplan** [comment]
@chrisgarrity yeah I noticed in 3.0 there are a lot of utility functions that don't require jsdoc because they are arrow functions. I guess that might be because they shouldn't be arrow functions (not sure if there is an eslint rule for "no-useless-arrow" or something). However, we probably don't want jsdoc on the react-components and their lifecycle methods.

**Comment by rschamp** [comment]
> `no-restricted-properties`: I actually missed this one when I was looking through the list. Do we use this right now?

It's in use, but I don't think it's warning anywhere. I think I can replace this this lint rule with PR comments :)
