### ISSUE TITLE
Mention `scratch` as a global

### ISSUE THREAD

**Issue by Richienb** [LLK/eslint-config-scratch#49]
It would be useful to add `scratch/env` that defined all of the globals that a Scratch extension script would be able to access.

**Comment by kenzievt** [comment]
hello

**Comment by kenzievt** [comment]
Scratch is blocked at our school.

**Comment by kenzievt** [comment]
> hello

hello

**Comment by benjiwheeler** [comment]
@Richienb Could you please say more about why this would be useful? I'm going to close it for now, but I'd be happy to reopen it if you can help me understand why this would help.

**Comment by Richienb** [comment]
I want to use the ESLint config for Scratch to develop a Scratch extension.
