### ISSUE TITLE
Update es6 config to demand `import` over `require`

### ISSUE THREAD

**Issue by paulkaplan** [LLK/eslint-config-scratch#9]
@rschamp I believe this is the right place for this right? I noticed in `scratch-gui` since we moved to `import` instead of `require`, we still have some left over requires that aren't being noticed by the linter.

**Comment by paulkaplan** [comment]
@rschamp what do you think about doing this directly in scratch-gui repo for now?

**Comment by rschamp** [comment]
Seeing as Node still doesn't support `import` syntax in 8, and may not for some time, this will be an issue in repos that import webpacked files for tests in Node. So for now, let's just use this rule in LLK/scratch-gui. In the future we may be able to resolve this by babel-ifying the test files? Not ideal, but possibly necessary for making the localization process not suck...
